force-app/main/default/objects/Apex_Aura_Action__c/Apex_Aura_Action__c.object-meta.xml
<CustomObject>
    <label>Apex/Aura Action</label>
    <nameField>
        <label>Apex/Aura Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Aura Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Aura_Action__c/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <label>Apex Class Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Aura_Action__c/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <label>Apex Method</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Aura_Action__c/fields/Argument_List__c.field-meta.xml
<CustomField>
    <fullName>Argument_List__c</fullName>
    <label>Argument List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Aura_Action__c/fields/Aura_LWC_Cmp_Name__c.field-meta.xml
<CustomField>
    <fullName>Aura_LWC_Cmp_Name__c</fullName>
    <label>Aura/LWC Cmp Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Action__c/Form_Action__c.object-meta.xml
<CustomObject>
    <label>Form Action</label>
    <nameField>
        <displayFormat>Action-{00000}</displayFormat>
        <label>Form Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Action__c/fields/Apex_Aura_Action__c.field-meta.xml
<CustomField>
    <fullName>Apex_Aura_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apex/AuraAction</label>
    <referenceTo>Apex_Aura_Action__c</referenceTo>
    <relationshipLabel>Apex Aura Actions</relationshipLabel>
    <relationshipName>Apex_Aura_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Action__c/fields/Event_Name_To_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Event_Name_To_Trigger__c</fullName>
    <label>Event Name To Trigger</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Action__c/fields/Field_Action__c.field-meta.xml
<CustomField>
    <fullName>Field_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Action</label>
    <referenceTo>Form_Field__c</referenceTo>
    <relationshipLabel>Field Actions</relationshipLabel>
    <relationshipName>Field_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Action__c/fields/Form_Template__c.field-meta.xml
<CustomField>
    <fullName>Form_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Template</label>
    <referenceTo>Form_Template__c</referenceTo>
    <relationshipLabel>Form Actions</relationshipLabel>
    <relationshipName>Form_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Action__c/fields/Invoke_For_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Invoke_For_Field_Value__c</fullName>
    <label>Invoke For Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Action__c/fields/Section_Action__c.field-meta.xml
<CustomField>
    <fullName>Section_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section Action</label>
    <referenceTo>Form_Section__c</referenceTo>
    <relationshipLabel>Section Actions</relationshipLabel>
    <relationshipName>Section_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Dependency__c/Form_Dependency__c.object-meta.xml
<CustomObject>
    <label>Form Dependency</label>
    <nameField>
        <displayFormat>Dependency-{00000}</displayFormat>
        <label>Form Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Dependency__c/fields/Controlling_Field__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Controlling Field</label>
    <referenceTo>Form_Field__c</referenceTo>
    <relationshipLabel>Field Dependencies</relationshipLabel>
    <relationshipName>Field_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Dependency__c/fields/Dependency_Type__c.field-meta.xml
<CustomField>
    <fullName>Dependency_Type__c</fullName>
    <label>Dependency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Hide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Dependency__c/fields/Dependent_Field__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dependent Field</label>
    <referenceTo>Form_Field__c</referenceTo>
    <relationshipLabel>Field Dependencies (Dependent Field)</relationshipLabel>
    <relationshipName>Field_Dependent_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Dependency__c/fields/Dependent_Section__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dependent Section</label>
    <referenceTo>Form_Section__c</referenceTo>
    <relationshipLabel>Section Dependencies</relationshipLabel>
    <relationshipName>Section_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Dependency__c/fields/On_Controlling_Value__c.field-meta.xml
<CustomField>
    <fullName>On_Controlling_Value__c</fullName>
    <label>On Controlling Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/Form_Field__c.object-meta.xml
<CustomObject>
    <label>Form Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Field__c/fields/Field_Section__c.field-meta.xml
<CustomField>
    <fullName>Field_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Section</label>
    <referenceTo>Form_Section__c</referenceTo>
    <relationshipLabel>Section Fields</relationshipLabel>
    <relationshipName>Section_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/fields/Field_Validation_Regex__c.field-meta.xml
<CustomField>
    <fullName>Field_Validation_Regex__c</fullName>
    <label>Field Validation Regex</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <label>Formula</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Field__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Section__c/Form_Section__c.object-meta.xml
<CustomObject>
    <label>Form Section</label>
    <nameField>
        <label>Form  Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Section__c/fields/Form_Template__c.field-meta.xml
<CustomField>
    <fullName>Form_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Template</label>
    <referenceTo>Form_Template__c</referenceTo>
    <relationshipLabel>Form Sections</relationshipLabel>
    <relationshipName>Form_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Section__c/fields/Parent_Form_Section__c.field-meta.xml
<CustomField>
    <fullName>Parent_Form_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Form Section</label>
    <referenceTo>Form_Section__c</referenceTo>
    <relationshipLabel>Child Form Sections</relationshipLabel>
    <relationshipName>Child_Form_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Section__c/fields/Section_Number__c.field-meta.xml
<CustomField>
    <fullName>Section_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Section Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Section__c/fields/Section_Type__c.field-meta.xml
<CustomField>
    <fullName>Section_Type__c</fullName>
    <label>Section Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accordion</fullName>
            </value>
            <value>
                <fullName>Vertical Tab</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Template__c/Form_Template__c.object-meta.xml
<CustomObject>
    <label>Form Template</label>
    <nameField>
        <displayFormat>Form-{00000}</displayFormat>
        <label>Form Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Template__c/fields/Form_Object__c.field-meta.xml
<CustomField>
    <fullName>Form_Object__c</fullName>
    <label>Form Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Template__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Record Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DynamicFormCreatorController.cls
public without sharing class DynamicFormCreatorController {
    private static Map<Id, Form_Section__c> mapOfSection;
    private static Map<Id, List<Id>> immediateChildMap;
    private static Set<Id> parentsSection;
    private static Map<String, List<sObject>> fieldActionMap;
    private static Map<String, List<sObject>> fieldDependenciesMap;
    private static Map<String, List<sObject>> fieldToSectionMap;
    @AuraEnabled(cacheable = true)
    public static FormTemplate getCurrentTemplate(Id templateId){
        try {
            if(!String.isBlank(templateId)){
                FormTemplate template = new FormTemplate();
                template.formTemplate = [Select Id,Form_Object__c, Form_type__c from Form_Template__c WHERE Id =: templateId WITH SECURITY_ENFORCED LIMIT 1];
                template.relatedFormActions = [Select Id,Event_Name_To_Trigger__c, Invoke_For_Field_Value__c, Apex_Aura_Action__r.Apex_Class_Name__c, Apex_Aura_Action__r.Apex_Method__c, 
                Apex_Aura_Action__r.Argument_List__c, Apex_Aura_Action__r.Aura_LWC_Cmp_Name__c, Form_Template__c from Form_Action__c  Where Form_Template__c =:templateId WITH SECURITY_ENFORCED LIMIT 49999 ];
                List<FormSection> formSections = new List<FormSection>();
                FormSection tempFormSection;
                parentsSection = new Set<Id>();
                immediateChildMap = new  Map<Id, List<Id>>();

                mapOfSection = new Map<Id, Form_Section__c>([Select Id,Name, Section_Number__c, Section_Type__c,Parent_Form_Section__c 
                ,(SELECT Id,Event_Name_To_Trigger__c, Invoke_For_Field_Value__c, Apex_Aura_Action__r.Apex_Class_Name__c,
                Apex_Aura_Action__r.Apex_Method__c, Apex_Aura_Action__r.Argument_List__c, Apex_Aura_Action__r.Aura_LWC_Cmp_Name__c, Form_Template__c
                FROM Section_Actions__r) FROM Form_Section__c WHERE Form_Template__c =: templateId WITH SECURITY_ENFORCED]);

                List<Form_Field__c> sectionFields = [Select Id,Field_API_Name__c,Field_Section__c, Field_Validation_Regex__c, Formula__c, Required__c, Type__c  
                FROM Form_Field__c WHERE Field_Section__c IN : mapOfSection.keyset() WITH SECURITY_ENFORCED];

                List<Form_Action__c> fieldActions = [Select Id,Event_Name_To_Trigger__c,Field_Action__c, Invoke_For_Field_Value__c, Apex_Aura_Action__r.Apex_Class_Name__c,
                Apex_Aura_Action__r.Apex_Method__c, Apex_Aura_Action__r.Argument_List__c, Apex_Aura_Action__r.Aura_LWC_Cmp_Name__c, Form_Template__c
                from Form_Action__c WHERE Field_Action__c IN (SELECT ID FROM Form_Field__c WHERE Field_Section__c IN: mapOfSection.keyset()) WITH SECURITY_ENFORCED];

                List<Form_Dependency__c> fieldDependencies = [Select Id,Controlling_Field__c, Dependency_Type__c, Dependent_Field__c, Dependent_Section__c, On_Controlling_Value__c
                from Form_Dependency__c WHERE Controlling_Field__c IN (SELECT ID FROM Form_Field__c WHERE Field_Section__c IN: mapOfSection.keyset()) WITH SECURITY_ENFORCED];
                fieldToSectionMap = genericMapCreatorBasedOnKey('Field_Section__c', sectionFields);
                fieldDependenciesMap = genericMapCreatorBasedOnKey('Controlling_Field__c', fieldDependencies);
                fieldActionMap = genericMapCreatorBasedOnKey('Field_Action__c', fieldActions);
                for(Form_Section__c section: mapOfSection.values()){
                    if(section.Parent_Form_Section__c == null && !immediateChildMap.containsKey(section.Id)){
                        parentsSection.add(section.Id);
                        immediateChildMap.put(section.Id, new List<Id>());
                        continue;
                    }else if(section.Parent_Form_Section__c == null && immediateChildMap.containsKey(section.Id)){
                        parentsSection.add(section.Id);
                        continue;
                    }
                    if(!immediateChildMap.containsKey(section.Parent_Form_Section__c)){
                        immediateChildMap.put(section.Parent_Form_Section__c, new List<Id>{section.Id});
                    }else{
                        immediateChildMap.get(section.Parent_Form_Section__c).add(section.Id);
                    }
                }
                FormSection tempSection;
                if(!parentsSection.isEmpty()){
                    /**section are there and run a for loop over to create a node */
                    for(Id parentSecId : parentsSection){
                        tempSection = new FormSection();
                        tempSection.formSection = mapOfSection.get(parentSecId);
                        tempSection.relatedSectionActions = mapOfSection.get(parentSecId).Section_Actions__r;
                        tempSection.sectionFields = getAllFieldForSection(parentSecId);
                        tempSection.childFormSection = recursiveSectionCreator(parentSecId);
                        formSections.add(tempSection);
                    }
                }
                template.formSections = formSections;
                System.debug(JSON.serializePretty(template));
                return template;
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    private static Map<String, List<sObject>> genericMapCreatorBasedOnKey(String key, List<sObject> iteratorList){
        Map<String, List<sObject>> genericMapWithStringKey = new Map<String, List<sObject>>();
        for(sObject eachObj: iteratorList){
            if(!eachObj.isSet(key)){
                continue;
            }
            if(genericMapWithStringKey.containsKey(String.valueOf(eachObj.get(key)))){
                genericMapWithStringKey.get(String.valueOf(eachObj.get(key))).add(eachObj);
            }else{
                genericMapWithStringKey.put(String.valueOf(eachObj.get(key)), new List<sObject>{eachObj});
            }
        }
        return genericMapWithStringKey;
    }
    private static List<FormField> getAllFieldForSection(Id sectionId){
        List<FormField> fields = new List<FormField>();
        FormField tempField;
        if(fieldToSectionMap.containsKey(sectionId)){
            for(sObject field: fieldToSectionMap.get(sectionId)){
                tempField = new FormField();
                tempField.formField = (Form_Field__c)field;
                tempField.relatedFieldActions = (List<Form_Action__c>)(!(fieldActionMap.containsKey((String)field.get('Id')))?new List<Form_Action__c>():fieldActionMap.get((String)field.get('Id')));
                tempField.controllingFieldDependency = (List<Form_Dependency__c>)(!(fieldDependenciesMap.containsKey((String)field.get('Id')))?new List<Form_Dependency__c>():fieldDependenciesMap.get((String)field.get('Id')));
                fields.add(tempField);
            }
        }
        return fields;
    }
    private static List<FormSection> recursiveSectionCreator(Id parentSectionId){
        FormSection tempSection;
        List<FormSection> formSections = new List<FormSection>();
        for(Id childSection: immediateChildMap.get(parentSectionId)){
            tempSection = new FormSection();
            tempSection.formSection = mapOfSection.get(childSection);
            tempSection.relatedSectionActions = mapOfSection.get(childSection).Section_Actions__r;
            tempSection.sectionFields = getAllFieldForSection(childSection);
            tempSection.childFormSection = (immediateChildMap.containsKey(childSection))?recursiveSectionCreator(childSection):null;
            formSections.add(tempSection);
        }
        return formSections;
    }
    @AuraEnabled(cacheable = true)
    public static Form_Action__c getActionRecord(Id actionId){
        try {
            return [Select Id,Apex_Aura_Action__r.Apex_Method__c, Apex_Aura_Action__r.Apex_Class_Name__c, Apex_Aura_Action__r.Argument_List__c,
             Apex_Aura_Action__r.Aura_LWC_Cmp_Name__c, Event_Name_To_Trigger__c, Field_Action__c, Form_Template__c, Invoke_For_Field_Value__c from Form_Action__c WHERE Id=: actionId WITH SECURITY_ENFORCED];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static list<sObject> fetchLookupData(string searchKey , string sObjectApiName) {   
        if(!checkIfObjectisAccessible(sObjectApiName)){
            throw new AuraHandledException('Object '+ sObjectApiName + ' is not accessible to this user.');
        } 
        List < sObject > returnList = new List < sObject > ();
        string sWildCardText = '%' + searchKey + '%';
        string sQuery = 'Select Id,Name From ' + sObjectApiName + ' Where Name Like : sWildCardText order by createdDate DESC LIMIT 5';
        for (sObject obj: database.query(String.escapeSingleQuotes(sQuery))) {
            returnList.add(obj);
        }
        return returnList;
    }
    private static Boolean checkIfObjectisAccessible(String objectName){
        Schema.DescribeSobjectResult[] results = Schema.describeSObjects(new List<String>{objectName});
        return results[0].isQueryable();

    }
    // Method to fetch lookup default value 
    @AuraEnabled
    public static sObject fetchDefaultRecord(string recordId , string sObjectApiName) {
        if(!checkIfObjectisAccessible(sObjectApiName)){
            throw new AuraHandledException('Object '+ sObjectApiName + ' is not accessible to this user.');
        } 
        string sRecId = recordId;    
        string sQuery = 'Select Id,Name From ' + sObjectApiName + ' Where Id = : sRecId LIMIT 1';
        for (sObject obj: database.query(String.escapeSingleQuotes(sQuery))) {
            return obj;
        }
        return null;
    }
    public class FormTemplate{
        @auraEnabled public Form_Template__c formTemplate;
        @auraEnabled public List<Form_Action__c> relatedFormActions;
        @auraEnabled public List<FormSection> formSections;

    }
    public class FormSection{
        @auraEnabled public Form_Section__c formSection;
        @auraEnabled public List<FormSection> childFormSection;
        @auraEnabled public List<Form_Action__c> relatedSectionActions;
        @auraEnabled public List<FormField> sectionFields;
    }
    public class FormField{
        @auraEnabled public Form_Field__c formField;  
        @auraEnabled public List<Form_Action__c> relatedFieldActions;  
        @auraEnabled public List<Form_Dependency__c> controllingFieldDependency;  
    }
}